[package]
name = "learning_actix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
config = "0.11"
juniper = "0.10"
serde = { version = "1.0", features = ["derive"] }